name: PostgreSQL Service Container with Restore

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: webappdb 
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: webappdb
      DATABASE_USER: testuser
      DATABASE_PASSWORD: testpass

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore PostgreSQL schema and data
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          PGPASSWORD=$DATABASE_PASSWORD psql \
            -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME \
            -f backup_webappdb.sql

      - name: Start application
        run: |
          export DATABASE_URL=postgresql://$DATABASE_USER:$DATABASE_PASSWORD@$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
          python run.py

      - name: Test app is running
        run: |
          curl http://127.0.0.1:8081/ping
